.PHONY: all clean
all:
	@echo Updating badge download counts...
	Rscript R/svg.R
	@echo Compiling CV...
	xelatex cv.tex
	@echo Removing aux files...
	rm *.out *.log *.aux
clean:
	@echo Removing aux files...
	rm *.out *.log *.aux
